### ISSUE TITLE
Issues deleting journal entries

### ISSUE THREAD

**Issue by nurkkala** [quantum-bits/galilee-webapp#10]
- Intermittently (but pretty regularly) after confirming the deletion of a journal entry, the dialog goes away but the screen stays dimmed.
- The calendar should update after a deletion.

**Comment by knkiers** [comment]
The issue with the screen staying dimmed is that the modal actually gets activated twice, I think.  (That's what it looks like in the console, and the screen is actually 'double-dark' during the time that the modal is present.)  Not sure what is causing this.

**Comment by knkiers** [comment]
The problem seems to be connected to the Subject that is issuing the command to launch the delete modal.  If you click delete, say yes or no, browse to another page in the app, and then come back and click delete, it appears that two 'delete' messages are sent out as Observables.  There must be an archived one that is still in the hopper or something.

**Comment by knkiers** [comment]
The problem was that we were not unsubscribing when leaving the page (we had multiple subscriptions to the 'delete' data stream, once for every time the page was loaded).  The ngOnDestroy life cycle hook needs to be used to unsubscribe upon leaving the page.  This seems to have fixed the issue.  I did a pre-emptive fix on the post-dashboard page, too.

**Comment by knkiers** [comment]
The calendar should update after a deletion -- I don't think this part has necessarily been fixed.

**Comment by knkiers** [comment]
added a new method, journal-dashboard.updateCalendar(), which refetches the metadata for the page; call this method after a successful delete
