### ISSUE TITLE
add endpoints to delete a question, add a question and update a question

### ISSUE THREAD

**Issue by knkiers** [quantum-bits/galilee-webapp#19]
- write reading-service method that can be called from update-questions-list.onDeleteQuestion()
...the array index of the question is available from within onDeleteQuestion(), as is the dateString; maybe it would be helpful to pass the readingDayId into update-questions-list as well...

- write reading-service method that can be called from update-questions-list.onAddQuestion()
...the array index of the question is available (either for editing or for tacking on at the end of the list, for a new question)

**Comment by nurkkala** [comment]
Questions are now being returned to the client as objects instead of strings. These objects include question IDs so that we can communicate more easily with the server.

**Comment by nurkkala** [comment]
The `UpdateQuestionFormComponent` knows whether it's creating a new question or updating an existing one. However, this information isn't getting back to the `QuestionListComponent`, where it's needed in order to determine which endpoint to invoke (`POST` or `PATCH`). Do we have to go back to the list component, or can we invoke the endpoint from the form component?

**Comment by knkiers** [comment]
I like your idea of doing the POST or PATCH directly from the form component.

**Comment by nurkkala** [comment]
Endpoints complete.
